// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdnQ5Lv_kXBJTFIWRR6rmJ9XGtA3zIcSM',
    appId: '1:112042211716:web:cc3d26fc2ae44d7bb945d1',
    messagingSenderId: '112042211716',
    projectId: 'grocery-app-ref-provider-task',
    authDomain: 'grocery-app-ref-provider-task.firebaseapp.com',
    storageBucket: 'grocery-app-ref-provider-task.appspot.com',
    measurementId: 'G-ZCDETMGVV2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCd6zKH8w8N1DSJSZE-OTsAJTleiLClVuc',
    appId: '1:112042211716:android:213e5037963cc9cdb945d1',
    messagingSenderId: '112042211716',
    projectId: 'grocery-app-ref-provider-task',
    storageBucket: 'grocery-app-ref-provider-task.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0jk1uyUobNEt0Xl7bWI8wGB5Q2cSVxCQ',
    appId: '1:112042211716:ios:c612f76242490fb8b945d1',
    messagingSenderId: '112042211716',
    projectId: 'grocery-app-ref-provider-task',
    storageBucket: 'grocery-app-ref-provider-task.appspot.com',
    iosBundleId: 'com.example.groceryTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0jk1uyUobNEt0Xl7bWI8wGB5Q2cSVxCQ',
    appId: '1:112042211716:ios:c612f76242490fb8b945d1',
    messagingSenderId: '112042211716',
    projectId: 'grocery-app-ref-provider-task',
    storageBucket: 'grocery-app-ref-provider-task.appspot.com',
    iosBundleId: 'com.example.groceryTask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDdnQ5Lv_kXBJTFIWRR6rmJ9XGtA3zIcSM',
    appId: '1:112042211716:web:a92ed102c9d0fd2cb945d1',
    messagingSenderId: '112042211716',
    projectId: 'grocery-app-ref-provider-task',
    authDomain: 'grocery-app-ref-provider-task.firebaseapp.com',
    storageBucket: 'grocery-app-ref-provider-task.appspot.com',
    measurementId: 'G-ESQF1ZMYYS',
  );
}
