// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYnm7tVjKAaIO-1qnKTsewYcl1UxXpBek',
    appId: '1:754449716900:web:622d33814a4ca889f1b831',
    messagingSenderId: '754449716900',
    projectId: 'grocery-app-ref-provider',
    authDomain: 'grocery-app-ref-provider.firebaseapp.com',
    storageBucket: 'grocery-app-ref-provider.appspot.com',
    measurementId: 'G-KEDERL57BM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWlStnTfXf4fGoVXMR5XOOpFPopFJubNs',
    appId: '1:754449716900:android:71eff046b0021c2ff1b831',
    messagingSenderId: '754449716900',
    projectId: 'grocery-app-ref-provider',
    storageBucket: 'grocery-app-ref-provider.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyM7cPA6HJ2o76wVqrdy4S0C9hxkUIRdA',
    appId: '1:754449716900:ios:d50e2076ccac1051f1b831',
    messagingSenderId: '754449716900',
    projectId: 'grocery-app-ref-provider',
    storageBucket: 'grocery-app-ref-provider.appspot.com',
    iosBundleId: 'com.example.groceryTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCyM7cPA6HJ2o76wVqrdy4S0C9hxkUIRdA',
    appId: '1:754449716900:ios:d50e2076ccac1051f1b831',
    messagingSenderId: '754449716900',
    projectId: 'grocery-app-ref-provider',
    storageBucket: 'grocery-app-ref-provider.appspot.com',
    iosBundleId: 'com.example.groceryTask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBYnm7tVjKAaIO-1qnKTsewYcl1UxXpBek',
    appId: '1:754449716900:web:5dde769925cdb833f1b831',
    messagingSenderId: '754449716900',
    projectId: 'grocery-app-ref-provider',
    authDomain: 'grocery-app-ref-provider.firebaseapp.com',
    storageBucket: 'grocery-app-ref-provider.appspot.com',
    measurementId: 'G-XCJTX62FKN',
  );
}
